const CANVAS_WIDTH = 400;
const CANVAS_HEIGHT = 400;
const ANIMATION_DURATION = 150;
const ANIMATE_DY = CANVAS_HEIGHT/9;
export {
    CANVAS_WIDTH,
    CANVAS_HEIGHT,
    ANIMATION_DURATION,
    ANIMATE_DY
};